default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      # set the recurring tasks
      recurring_tasks:
        backup_contacts_job:
          class: BackupContactsJob
          # schedule uses anything that Fugit parses/accepts as a cron expression
          
          # every minute on second 5
          # schedule: 5 * * * * *

          # every day at midnight
          schedule: "@daily"

  #####
  # workers:
  #   - queues: "*"
  #     threads: 5
  #     processes: 1
  #     polling_interval: 0.1
  #####
      


development:
 <<: *default

test:
 <<: *default

production:
 <<: *default
